### ISSUE TITLE
Sidebar+ made some sites broken

### ISSUE THREAD

**Issue by zephyrer** [zluca/Sidebar#13] opened 2018-01-24 06:29 UTC
I met two sites broken by Sidebar+:

1. When Sidebar+ enabled, the item page of pan.baidu.com couldn't completely load. The first of following figures is broken page, the second is normal.
![broken](https://user-images.githubusercontent.com/2318618/35315949-00b597b8-010a-11e8-920a-d284a939387c.png)
![normal](https://user-images.githubusercontent.com/2318618/35315950-045a3586-010a-11e8-8491-d807c8f08525.png)

2. Chapter page of vipreader.qidian.com: if Sidebar+ enabled, when clicking the subscription buttons there's no subscription dialog popuped, which should like the following figure.
![subscribe-popup](https://user-images.githubusercontent.com/2318618/35317601-846b63c8-0112-11e8-8ff8-9f007adb07ae.png)

**Comment by zluca** [comment] 2018-01-24 13:11
>the item page of pan.baidu.com
>Chapter page of vipreader.qidian.com

Can you give me direct links to this pages? I'm not good in Chinese. =)

Or if it requires registration plz make testing if it broken both in Chrome and Firefox.

**Comment by zluca** [comment] 2018-01-26 17:04
@zephyrer 
Ok i figured out what possible does such a mess. Can you test it or give me direct links to broken pages?

**Comment by zephyrer** [comment] 2018-01-26 18:29
I noticed when pages broken. there's an error msg:
Error: Permission denied to access property "apply"

Please try the url: https://pan.baidu.com/s/1kVCGnor

**Comment by zluca** [comment] 2018-01-26 18:48
> url
Thank you, now i can reproduce this bug. First look shows that this is a specific Firefox issue. I will do more research tomorrow.

**Comment by zluca** [comment] 2018-01-28 16:25
@zephyrer 
It looks like 0.4.15 finally fixes stuff. But I want you to check all pages before I close this issue. :)

**Comment by zluca** [comment] 2018-02-12 16:55
Ok. Due to topic author staing silent i assume that bug is fixed.

**Closed by zluca** 2018-02-12 16:55 UTC
Labels: bug, firefox

**Comment by zephyrer** [comment] 2018-02-13 18:02
Sorry for the late reply. The two sites are OK now. Thanks alot.
